dist: xenial
language: node_js
cache: npm
node_js:
  - "10"

services:
  - docker

before_install:
  - docker pull jojomi/hugo:0.55

install: false
# script - run the build script
script:
    - (cd vue-components && npm ci && npm run build)
    - docker run -v $(pwd):/src -v $(pwd)/public:/output jojomi/hugo:0.53

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  verbose: true
  keep-history: true
  local-dir: public
  target_branch: master  # branch contains blog content
  on:
    branch: develop  # branch contains Hugo generator code
